state = {
    "Andhra Pradesh": [
        "Amruta Balli",
        "Ashwagandha",
        "Curry Leaf",
        "Doddapatre",
        "Ganike",
        "Guava",
        "Jasmine",
        "Lemon Grass",
        "Mint",
        "Papaya",
        "Tulsi",
    ],
    "Arunachal Pradesh": ["Bamboo"],
    "Assam": ["Betel", "Bamboo", "Betel Nut", "Geranium"],
    "Bihar": ["Amla", "Guava"],
    "Gujarat": [
        "Aloe Vera",
        "Castor",
        "Guava",
        "Henna",
        "Mango",
        "Nagadali",
        "Neem",
        "Pomegranate",
        "Tulsi",
        "Betel Nut",
    ],
    "Haryana": [
        "Aloe Vera",
        "Amla",
        "Castor",
        "Ganike",
        "Guava",
        "Neem",
        "Pomegranate",
        "Tulsi",
    ],
    "Himachal Pradesh": ["Ashwagandha", "Bamboo", "Geranium", "Jasmine"],
    "Jammu Kashmir": ["Bamboo"],
    "Jharkhand": ["Aloe Vera", "Guava"],
    "Karnataka": [
        "Aloe Vera",
        "Amruta Balli",
        "Ashoka",
        "Ashwagandha",
        "Avocado",
        "Basale",
        "Brahmi",
        "Castor",
        "Curry Leaf",
        "Doddapatre",
        "Ganike",
        "Guava",
        "Geranium",
        "Hibiscus",
        "Jasmine",
        "Lemon Grass",
        "Mango",
        "Mint",
        "Neem",
        "Nithyapushpa",
        "Papaya",
        "Pepper",
        "Sapota",
        "Tulasi",
        "Wood sorrel"
    ],
    "kerala": [
        "Amruta Balli",
        "Ashoka",
        "Ashwagandha",
        "Avocado",
        "Basale",
        "Brahmi",
        "Castor",
        "Curry Leaf",
        "Doddapatre",
        "Ganike",
        "Guava",
        "Hibiscus",
        "Insulin Plant",
        "Jasmine",
        "Lemon Grass",
        "Mint",
        "Nooni",
        "Papaya",
        "Pepper",
        "Tulasi",
    ],
    "Madhya Pradesh": [
        "Amla",
        "Ashwagandha",
        "Castor",
        "Doddapatre",
        "Ekka",
        "Ganike",
        "Guava",
        "Hibiscus",
        "Raktachandini",
        "Tulasi",
    ],
    "Maharashtra": [
        "Aloe Vera",
        "Castor",
        "Curry Leaf",
        "Doddapatre",
        "Geranium",
        "Hibiscus",
        "Insulin Plant",
        "Jasmine",
        "Lemon",
        "Mango",
        "Pomegranate",
        "Rose",
        "Sapota",
        "Tulasi",
    ],
    "Manipur": ["Bamboo"],
    "Meghalaya": ["Bamboo"],
    "Mizoram": ["Bamboo"],
    "Nagaland": ["Bamboo"],
    "Odisha": [
        "Amla",
        "Betel",
        "Brahmi",
        "Castor",
        "Guava",
        "Neem",
        "Pomegranate",
        "Raktachandini",
    ],
    "Punjab": [
        "Aloe Vera",
        "Amla",
        "Castor",
        "Ganike",
        "Guava",
        "Mint",
        "Neem",
        "Pomegranate",
        "Tulasi",
    ],
    "Rajasthan": [
        "Amla",
        "Ashwagandha",
        "Castor",
        "Doddapatre",
        "Ekka",
        "Ganike",
        "Guava",
        "Henna",
        "Neem",
        "Pomegranate",
        "Raktachandini",
        "Tulasi",
    ],
    "Sikkim": ["Bamboo"],
    "Tamil Nadu": [
        "Amruta Balli",
        "Ashoka",
        "Ashwagandha",
        "Avocado",
        "Basale",
        "Brahmi",
        "Castor",
        "Curry Leaf",
        "Doddapatre",
        "Ganike",
        "Guava",
        "Hibiscus",
        "Insulin Plant",
        "Jasmine",
        "Lemon Grass",
        "Mango",
        "Mint",
        "Neem",
        "Nithyapushpa",
        "Nooni",
        "Papaya",
        "Pepper",
        "Rose",
        "Sapota",
        "Tulasi",
        "Wood sorrel"
    ],
    "Telangana": [
        "Aloe Vera",
        "Ashwagandha",
        "Curry Leaf",
        "Doddapatre",
        "Guava",
        "Jasmine",
        "Lemon Grass",
        "Mint",
        "Papaya",
        "Tulasi",
    ],
    "Tripura": ["Bamboo"],
    "Uttar Pradesh": [
        "Amla",
        "Ashwagandha",
        "Brahmi",
        "Castor",
        "Curry Leaf",
        "Doddapatre",
        "Ganike",
        "Guava",
        "Hibiscus",
        "Jasmine",
        "Lemon",
        "Mint",
        "Neem",
        "Pomegranate",
        "Raktachandini",
        "Tulasi",
    ],
    "Uttarakhand": ["Ashwagandha", "Bamboo", "Geranium", "Jasmine", "Lemon Grass"],
    "West Bengal": [
        "Betel",
        "Bamboo",
        "Guava",
        "Hibiscus",
        "Jasmine",
        "Lemon Grass",
        "Pomegranate",
        "Rose",
        "Tulasi",
    ],
}



def stateMyPoint(predict):
    result = []
    for i in state:
        if predict in state.get(i):
            result.append(i)
    string = ""
    if len(result) != 0:
       for i in range(len(result)):
             if len(result) != i + 1:
                    string += f"{result[i]} ,"
             else:
                    string += f"{result[i]}."

    else:
        string="Nothing"
    return string